class State():
    IDLE = "IDLE"
    NAVIGATION = "NAVIGATION"
    RECOGNITION = "RECOGNITION"
    COLLECTION = "COLLECTION"

class Signal():
    NEW_LOCATION = "NEW_LOCATION"
    ARRIVED = "ARRIVED"
    RECOGNIZED = "RECOGNIZED"
    COLLECTED = "COLLECTED"
    FAILED_NAVIGATION = "FAILED_NAVIGATION"
    FAILED_RECOGNITION = "FAILED_RECOGNITION"
    HALT = "HALT"