<?xml version="1.0"?>
<package format="3">
  <name>gripperx_arm</name>
  <version>0.1.0</version>
  <description>LeRobot SO-ARM100 action server for GripperX</description>
  <maintainer email="theo.blaesse@itq.de">Theo Blässe</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>gripperx_arm_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
