#!/usr/bin/env python3
"""Perform the Phase 1 edits mechanically, so the intervention is minutes long.

WHY A SCRIPT AND NOT JUST DOING IT
    Every Phase 1 edit lands in a file some other session may also be editing.
    The cost of the intervention is not the typing, it is the window during
    which this branch holds changes to shared files and can conflict. A script
    that is written, reviewed and dry-run in advance collapses that window to
    one command plus a test run.

    It also makes the change reviewable BEFORE it exists: --dry-run prints the
    exact diff, so the manifest is generated from the real edit rather than
    written by hand alongside it and drifting from it.

WHAT IT DOES
    1. Node defaults -> Parameter.Type.DOUBLE. A node that cannot find its
       parameter file then fails at startup instead of running on a stale
       literal. This is the change that has the most value and the least code.
    2. The tape pair a=0.180 / b=0.110 -> the CAD pair 0.1809 / 0.1087 in the
       three control configs, per the GQ-1 decision of 2026-08-21.
    3. Test files import gripperx_geometry.constants instead of carrying
       literals.
    4. package.xml gains the dependency where a test now imports it.

WHAT IT DELIBERATELY DOES NOT DO
    It does not rewrite the prose. The comment blocks in those YAMLs carry the
    measurement history and the OP-29 reasoning, which is the most valuable
    text in the repo and must not be regenerated by a regex. Every remaining
    prose mention of a superseded number is REPORTED instead, for a human pass.

USAGE
    python3 scripts/phase1_migrate.py --src-root <ws>/Software/ros2/src
    python3 scripts/phase1_migrate.py --src-root ... --apply
"""

from __future__ import annotations

import argparse
import difflib
import re
import sys
from pathlib import Path

# --------------------------------------------------------------------------
# The edit set, declared rather than scattered through the code
# --------------------------------------------------------------------------

POINTER = "declared in gripperx_geometry/config/geometry.yaml"

# 1. node defaults -> mandatory
#
# swerve_cmd_node.py was a fourth entry here and was REMOVED 2026-08-25 (user
# decision): the deletion round retired that node together with
# joint_command_bridge, sim_steer_bridge and control.launch.py, so migrating its
# literals would have been work on a file that no longer exists -- and because
# this script refuses to write anything when a single edit does not match, the
# missing file would have ABORTED the whole migration rather than skipping one
# target. Nothing else in the edit set changes.
NODE_DEFAULTS = {
    "gripperx_control/src/gripperx_control/teleop_joint_commands_node.py": ["a", "b", "wheel_radius"],
    "gripperx_teleop/gripperx_teleop/keyboard_teleop_node.py": ["a", "b", "wheel_radius"],
    "gripperx_localization/src/gripperx_localization/localization_input_node.py": ["effective_wheel_radius"],
}

# 2. the GQ-1 correction, tape -> CAD
VALUE_FIXES = {
    "gripperx_control/config/swerve_cmd.yaml": {"a": ("0.180", "0.1809"), "b": ("0.110", "0.1087")},
    "gripperx_control/config/teleop_joint_commands.yaml": {"a": ("0.180", "0.1809"), "b": ("0.110", "0.1087")},
    "gripperx_control/config/ros2_controllers.yaml": {"a": ("0.180", "0.1809"), "b": ("0.110", "0.1087")},
}

# 3. test literals -> imports
# The test files put their imports after a sys.path insert, so they already sit
# below module level and already carry noqa markers. Matching that keeps flake8
# quiet without changing anybody's lint configuration.
TEST_IMPORT = (
    "from gripperx_geometry.constants import (  # noqa: E402\n"
    "    HALF_TRACK_KINGPIN as B,\n"
    "    HALF_WHEELBASE_KINGPIN as A,\n"
    "    WHEEL_RADIUS_EFFECTIVE as WHEEL_RADIUS,\n"
    ")\n"
)
TEST_CONSTANTS = {
    "gripperx_control/test/check_steering_limits.py": ("A", "B", "WHEEL_RADIUS"),
    "gripperx_teleop/test/check_manoeuvres.py": ("A", "B", "WHEEL_RADIUS"),
}
TEST_MODEL_CALL = ["gripperx_teleop/test/check_teleop_manoeuvre_path.py"]
TEST_SHORT_NAMES = {"gripperx_swerve_controller/test/dump_reference.py": {"A": "A", "B": "B", "R": "WHEEL_RADIUS"}}

# 4. dependency edges the imports create
PACKAGE_DEPS = [
    "gripperx_control/package.xml",
    "gripperx_teleop/package.xml",
    "gripperx_swerve_controller/package.xml",
]

# 4b. C++ carries the same duplicates, found by the 2026-08-24 whole-tree sweep.
#     swerve_controller.hpp's members are auto_declare FALLBACKS — what the
#     controller uses if its YAML lacks the key — i.e. exactly the Python
#     declare_parameter defect in another language. The three test files derive
#     their expectations FROM these constants (verified: test_swerve_kinematics
#     builds its module table from kA/kB, test_steering_limits asserts limits
#     that do not depend on them), so changing them is self-consistent.
#     dump_reference.cpp and dump_reference.py must move TOGETHER — they are a
#     cross-language equivalence check and would otherwise disagree by design.
CPP_VALUE_FIXES = {
    "gripperx_swerve_controller/include/gripperx_swerve_controller/swerve_controller.hpp": [
        (r"double a_\{0\.180\}", "double a_{0.1809}"),
        (r"double b_\{0\.110\}", "double b_{0.1087}"),
    ],
    "gripperx_swerve_controller/test/dump_reference.cpp": [
        (r"constexpr double kA = 0\.180", "constexpr double kA = 0.1809"),
        (r"constexpr double kB = 0\.110", "constexpr double kB = 0.1087"),
    ],
    "gripperx_swerve_controller/test/test_swerve_kinematics.cpp": [
        (r"constexpr double kA = 0\.180", "constexpr double kA = 0.1809"),
        (r"constexpr double kB = 0\.110", "constexpr double kB = 0.1087"),
        # The spin pose is DERIVED from kA/kB. Pinning it as a literal is the
        # same defect as a hard-coded parameter default: it survives a geometry
        # change and then asserts the old robot. Derive it.
        (r"  const std::array<double, kNumWheels> expected_deg\{-58\.570, 58\.570, -58\.570, 58\.570\};",
         "  const double kSpinPoseDeg = std::atan2(kA, kB) / kDeg;\n"
         "  const std::array<double, kNumWheels> expected_deg{\n"
         "    -kSpinPoseDeg, kSpinPoseDeg, -kSpinPoseDeg, kSpinPoseDeg};"),
        # Likewise the king-pin arc per radian: that IS hypot(a, b), by definition.
        (r"EXPECT_NEAR\(std::fabs\(before\[i\]\.speed\) / spin\.omega, 0\.210950, 1e-6\)",
         "EXPECT_NEAR(std::fabs(before[i].speed) / spin.omega, std::hypot(kA, kB), 1e-6)"),
        # Per-wheel speeds keep the 0.2 mm FR asymmetry, which no one-line
        # derivation reproduces, so they stay literal — but regenerated for the
        # CAD geometry and labelled so the next change does not miss them.
        (r"  const std::array<double, kNumWheels> expected_rad_s\{-2\.8878, -2\.8878, 2\.8878, 2\.8857\};",
         "  // GEOMETRY-DERIVED, regenerated 2026-08-24 for a = 0.1809 / b = 0.1087.\n"
         "  // Not independent evidence: only the 0.266571 below is measured.\n"
         "  const std::array<double, kNumWheels> expected_rad_s{\n"
         "    -2.888884, -2.888884, 2.888874, 2.886717};"),
        # The name asserted a value that has now moved. Keep the history, drop
        # the number from the identifier.
        (r"SpinPoseIsFiftyEightPointFiveSevenDegreesNotFiftyPointSeven",
         "SpinPoseFollowsTheDeclaredGeometryNotTheRetiredOne"),
        (r"  EXPECT_NEAR\(std::atan2\(kA, kB\) / kDeg, 58\.570, 1e-3\);",
         "  // Retired geometry b = 0.16556 gave 50.80 deg; the tape pair\n"
         "  // 0.180 / 0.110 gave 58.57; the CAD pair 0.1809 / 0.1087 gives 59.00.\n"
         "  // Asserted as a RANGE against the retired value rather than as a new\n"
         "  // literal, so the next legitimate geometry change does not have to\n"
         "  // edit this test at all.\n"
         "  EXPECT_GT(std::atan2(kA, kB) / kDeg, 55.0);\n"
         "  EXPECT_LT(std::atan2(kA, kB) / kDeg, 62.0);"),
    ],
    "gripperx_swerve_controller/test/test_steering_limits.cpp": [
        (r"SwerveKinematics model\(0\.180, 0\.110, 0\.070\)",
         "SwerveKinematics model(0.1809, 0.1087, 0.070)"),
        # omega after the tight-cornering reduction is a function of a and b.
        (r"0\.2724288940429687", "0.2724380493164062"),
    ],
}

# 4c. the localization node's wheel_positions default — a correct list today,
#     and a second source of truth regardless.
LIST_DEFAULTS = {
    "gripperx_localization/src/gripperx_localization/localization_input_node.py": "wheel_positions",
}

# 5. the registry, which every edit above is designed to empty
REGISTRY_FILE = "gripperx_geometry/test/test_geometry_consistency.py"
REGISTRY_EMPTY = """KNOWN_DIVERGENCES: dict[str, tuple[float, str]] = {
    # EMPTIED BY PHASE 1, 2026-08-21. Every site that held a geometry value now
    # either agrees with the declaration, delegates it to a parameter file, or
    # imports it. Nothing is registered because nothing diverges.
    #
    # An entry belongs here only while a KNOWN divergence is waiting on a
    # decision or a scheduled fix. It is not a place to park a failure.
}"""


# 6. keyboard_teleop_node has NO parameter file on any launch path — found by
#    the 2026-08-21 dry run, which is exactly what a dry run is for. Removing
#    its defaults without giving it a file would break laptop_teleop.launch.py
#    at startup. The file is created rather than the values inlined into the
#    launch, because an inline literal is a new source of truth.
KEYBOARD_CONFIG = "gripperx_teleop/config/keyboard_teleop.yaml"

LAUNCH_FILE = "gripperx_teleop/launch/laptop_teleop.launch.py"
TEST_HARNESS = "gripperx_teleop/test/check_teleop_manoeuvre_path.py"
TELEOP_SETUP = "gripperx_teleop/setup.py"


# prose that will still name a superseded number afterwards
SUPERSEDED = ("0.203", "0.16556", "0.180", "0.110")


# --------------------------------------------------------------------------
# Edits
# --------------------------------------------------------------------------


def _ensure_parameter_import(text: str) -> str:
    if "from rclpy.parameter import Parameter" in text:
        return text
    anchor = "from rclpy.node import Node"
    if anchor not in text:
        raise RuntimeError("cannot place the Parameter import: no `from rclpy.node import Node`")
    return text.replace(anchor, anchor + "\nfrom rclpy.parameter import Parameter", 1)


def edit_node_defaults(text: str, names: list[str]) -> str:
    for name in names:
        pattern = re.compile(
            rf"(declare_parameter\(\s*(['\"]){re.escape(name)}\2\s*,\s*)"
            rf"[-+]?\d+(?:\.\d+)?"
        )
        text, count = pattern.subn(rf"\g<1>Parameter.Type.DOUBLE", text)
        if not count:
            raise RuntimeError(f"no numeric declare_parameter for {name!r}")
    return _ensure_parameter_import(text)


def edit_values(text: str, fixes: dict[str, tuple[str, str]]) -> str:
    for key, (old, new) in fixes.items():
        pattern = re.compile(rf"^(\s*){re.escape(key)}:\s*{re.escape(old)}\s*$", re.M)
        if not pattern.search(text):
            raise RuntimeError(f"{key}: expected value {old} not found")
        text = pattern.sub(rf"\g<1>{key}: {new}   # {POINTER}", text)
    return text


def edit_test_constants(text: str, names: tuple[str, ...]) -> str:
    first = None
    for name in names:
        pattern = re.compile(rf"^{name}\s*=\s*[-+]?\d+(?:\.\d+)?\s*$", re.M)
        match = pattern.search(text)
        if not match:
            raise RuntimeError(f"no module-level constant {name}")
        if first is None:
            first = match.start()
        text = pattern.sub("", text, count=1)
    lines = text[:first].rstrip("\n") + "\n" + TEST_IMPORT + "\n\n" + text[first:].lstrip("\n")
    return re.sub(r"\n{4,}", "\n\n\n", lines)


def edit_model_call(text: str) -> str:
    pattern = re.compile(
        r"FourWIS4WIDKinematicModel\(\s*a=[-+]?\d+(?:\.\d+)?\s*,\s*"
        r"b=[-+]?\d+(?:\.\d+)?\s*,\s*wheel_radius=[-+]?\d+(?:\.\d+)?\s*\)"
    )
    if not pattern.search(text):
        raise RuntimeError("no literal FourWIS4WIDKinematicModel(...) call")
    text = pattern.sub("FourWIS4WIDKinematicModel(a=A, b=B, wheel_radius=WHEEL_RADIUS)", text)
    anchor = "from gripperx_control.swerve_kinematic_model import FourWIS4WIDKinematicModel"
    line = [ln for ln in text.splitlines() if ln.startswith(anchor)]
    if not line:
        raise RuntimeError("cannot place the constants import")
    return text.replace(line[0], line[0] + "\n" + TEST_IMPORT.rstrip("\n"), 1)


def edit_short_names(text: str, mapping: dict[str, str]) -> str:
    first = None
    for local in mapping:
        pattern = re.compile(rf"^{local}\s*=\s*[-+]?\d+(?:\.\d+)?\s*$", re.M)
        match = pattern.search(text)
        if not match:
            raise RuntimeError(f"no module-level constant {local}")
        if first is None:
            first = match.start()
        text = pattern.sub("", text, count=1)
    canonical_of = {
        "A": "HALF_WHEELBASE_KINGPIN",
        "B": "HALF_TRACK_KINGPIN",
        "WHEEL_RADIUS": "WHEEL_RADIUS_EFFECTIVE",
    }
    # Sorted by the IMPORTED name, which is what ament_flake8's I101 checks —
    # sorting by the alias passes review and fails the linter.
    pairs = sorted(
        ((canonical_of[source], local) for local, source in mapping.items()),
        key=lambda pair: pair[0],
    )
    imports = "from gripperx_geometry.constants import (  # noqa: E402\n"
    for canonical, local in pairs:
        imports += f"    {canonical} as {local},\n"
    imports += ")\n"
    text = text[:first].rstrip("\n") + "\n" + imports + "\n\n" + text[first:].lstrip("\n")
    return re.sub(r"\n{4,}", "\n\n\n", text)


def keyboard_config_content(src_root: Path) -> str:
    """The parameter file keyboard_teleop_node has never had, from the source."""
    sys.path.insert(0, str(src_root / "gripperx_geometry" / "src"))
    from gripperx_geometry.generate import emit_param_fragments  # noqa: E402
    from gripperx_geometry.inventory import load_source  # noqa: E402

    source = load_source(src_root)
    values = {
        "a": "half_wheelbase_kingpin",
        "b": "half_track_kingpin",
        "wheel_radius": "wheel_radius_effective",
    }
    lines = [
        "# GENERATED FROM gripperx_geometry/config/geometry.yaml — DO NOT EDIT",
        "# Edit the quantity there and regenerate; edits here are lost.",
        "#",
        "# keyboard_teleop_node builds a FourWIS4WIDKinematicModel to predict the",
        "# pose swerve_cmd_node will command, and its arming guard compares that",
        "# prediction against the measured steering. Until 2026-08-21 it had no",
        "# parameter file at all and fell back on in-code defaults carrying the",
        "# obsolete a=0.203 / b=0.16556 pair — so the prediction was 7.77 deg off",
        "# the pose actually commanded, on every wheel, for in-place spin.",
        "",
        "keyboard_teleop_node:",
        "  ros__parameters:",
    ]
    for param, quantity in values.items():
        spec = source["quantities"][quantity]
        lines.append(f"    {param}: {spec['value']:.{spec['decimals']}f}")
    return "\n".join(lines) + "\n"


def edit_launch(text: str) -> str:
    """Point laptop_teleop.launch.py at the new parameter file."""
    if "keyboard_teleop.yaml" in text:
        return text
    anchor = "            parameters=[{"
    if anchor not in text:
        raise RuntimeError("cannot find keyboard_teleop_node's parameters=[{ block")
    replacement = (
        "            parameters=[\n"
        "                os.path.join(\n"
        "                    get_package_share_directory('gripperx_teleop'),\n"
        "                    'config', 'keyboard_teleop.yaml'),\n"
        "                {"
    )
    text = text.replace(anchor, replacement, 1)
    if "import os" not in text:
        text = text.replace("from launch import LaunchDescription",
                            "import os\n\nfrom ament_index_python.packages import get_package_share_directory\n"
                            "from launch import LaunchDescription", 1)
    return text


def edit_test_harness(text: str) -> str:
    """Give the in-process KeyboardTeleopNode the geometry it now requires."""
    if "f\"a:={A}\"" in text:
        return text
    anchor = '                "-p", "publish_rate_hz:=50.0",'
    if anchor not in text:
        raise RuntimeError("cannot find the rclpy.init parameter list")
    return text.replace(
        anchor,
        anchor + "\n"
        '                "-p", f"a:={A}",\n'
        '                "-p", f"b:={B}",\n'
        '                "-p", f"wheel_radius:={WHEEL_RADIUS}",',
        1,
    )


def edit_teleop_setup(text: str) -> str:
    if "keyboard_teleop.yaml" in text:
        return text
    anchor = "['config/teleop_mux.yaml']"
    if anchor not in text:
        raise RuntimeError("cannot find the config data_files entry")
    return text.replace(anchor, "['config/teleop_mux.yaml', 'config/keyboard_teleop.yaml']", 1)


def edit_cpp_values(text: str, fixes: list) -> str:
    for pattern, replacement in fixes:
        text, count = re.subn(pattern, replacement, text)
        if not count:
            raise RuntimeError(f"pattern not found: {pattern}")
    return text


def edit_list_default(text: str, name: str) -> str:
    """Drop a list-valued default, same reasoning as the scalar ones."""
    pattern = re.compile(
        rf"(declare_parameter\(\s*(['\"]){re.escape(name)}\2\s*,\s*)\[.*?\](\s*,?\s*\))",
        re.S)
    if not pattern.search(text):
        raise RuntimeError(f"no list default for {name!r}")
    text = pattern.sub(r"\g<1>Parameter.Type.DOUBLE_ARRAY\g<3>", text)
    return _ensure_parameter_import(text)


def edit_registry(text: str) -> str:
    """Empty the divergence registry — the point of every other edit."""
    pattern = re.compile(r"KNOWN_DIVERGENCES: dict\[str, tuple\[float, str\]\] = \{.*?\n\}", re.S)
    if not pattern.search(text):
        raise RuntimeError("cannot find the KNOWN_DIVERGENCES block")
    return pattern.sub(REGISTRY_EMPTY, text)


def edit_package_dep(text: str) -> str:
    """Add the test dependency, tolerating the two manifest shapes in this tree.

    Most packages group their <test_depend> entries; gripperx_teleop has none at
    all and goes straight from <exec_depend> to <export>. Anchoring only on
    <test_depend> made the whole migration refuse to run because of one file,
    which is the right failure but the wrong cause.
    """
    if "gripperx_geometry" in text:
        return text
    entry = "  <test_depend>gripperx_geometry</test_depend>\n"
    for anchor in ("  <test_depend>", "  <export>"):
        if anchor in text:
            return text.replace(anchor, entry + anchor, 1)
    raise RuntimeError("no <test_depend> or <export> to anchor the dependency to")


# --------------------------------------------------------------------------
# Driver
# --------------------------------------------------------------------------


def build_edits(root: Path) -> tuple[dict[Path, tuple[str, str]], list[str]]:
    edits: dict[Path, tuple[str, str]] = {}
    problems: list[str] = []

    def stage(relpath: str, fn):
        """Apply one edit, composing with any edit already staged for this file.

        Two edits touch check_teleop_manoeuvre_path.py — the model call and the
        harness parameter list. Reading from disk each time made the second
        silently discard the first, which the dry run caught by the harness
        referencing a name the discarded edit would have imported. Staged text
        is therefore chained, and the original is kept only for the diff.
        """
        path = root / relpath
        if not path.is_file():
            problems.append(f"{relpath}: file not found")
            return
        original, current = edits.get(path, (None, None))
        if original is None:
            original = current = path.read_text()
        try:
            after = fn(current)
        except RuntimeError as exc:
            problems.append(f"{relpath}: {exc}")
            return
        if original != after:
            edits[path] = (original, after)

    for relpath, names in NODE_DEFAULTS.items():
        stage(relpath, lambda t, n=names: edit_node_defaults(t, n))
    for relpath, fixes in VALUE_FIXES.items():
        stage(relpath, lambda t, f=fixes: edit_values(t, f))
    for relpath, names in TEST_CONSTANTS.items():
        stage(relpath, lambda t, n=names: edit_test_constants(t, n))
    for relpath in TEST_MODEL_CALL:
        stage(relpath, edit_model_call)
    for relpath, mapping in TEST_SHORT_NAMES.items():
        stage(relpath, lambda t, m=mapping: edit_short_names(t, m))
    for relpath in PACKAGE_DEPS:
        stage(relpath, edit_package_dep)
    for relpath, fixes in CPP_VALUE_FIXES.items():
        stage(relpath, lambda t, f=fixes: edit_cpp_values(t, f))
    for relpath, name in LIST_DEFAULTS.items():
        stage(relpath, lambda t, n=name: edit_list_default(t, n))
    stage(LAUNCH_FILE, edit_launch)
    stage(TEST_HARNESS, edit_test_harness)
    stage(TELEOP_SETUP, edit_teleop_setup)
    stage(REGISTRY_FILE, edit_registry)

    return edits, problems


def prose_residue(root: Path) -> list[str]:
    """Lines that will still name a superseded number after the edits."""
    out = []
    for relpath in list(VALUE_FIXES) + list(NODE_DEFAULTS):
        path = root / relpath
        if not path.is_file():
            continue
        for number, line in enumerate(path.read_text().splitlines(), 1):
            stripped = line.strip()
            if not (stripped.startswith("#") or stripped.startswith("//")):
                continue
            if any(value in line for value in SUPERSEDED):
                out.append(f"{relpath}:{number}: {stripped[:96]}")
    return out


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--src-root", type=Path, required=True)
    parser.add_argument("--apply", action="store_true", help="write the edits (default: show them)")
    parser.add_argument("--quiet-prose", action="store_true", help="skip the prose-residue report")
    args = parser.parse_args(argv)

    edits, problems = build_edits(args.src_root)

    new_file = args.src_root / KEYBOARD_CONFIG
    creating = not new_file.exists()

    if problems:
        print("PROBLEMS — nothing was written:")
        for problem in problems:
            print(f"  {problem}")
        return 1

    for path, (before, after) in sorted(edits.items()):
        relpath = path.relative_to(args.src_root)
        if args.apply:
            path.write_text(after)
            print(f"patched {relpath}")
        else:
            print("".join(difflib.unified_diff(
                before.splitlines(keepends=True), after.splitlines(keepends=True),
                fromfile=f"a/{relpath}", tofile=f"b/{relpath}",
            )), end="")

    if creating:
        content = keyboard_config_content(args.src_root)
        if args.apply:
            new_file.parent.mkdir(parents=True, exist_ok=True)
            new_file.write_text(content)
            print(f"created {KEYBOARD_CONFIG}")
        else:
            print(f"--- /dev/null\n+++ b/{KEYBOARD_CONFIG}")
            print("".join(f"+{line}\n" for line in content.splitlines()), end="")

    print(f"\n{len(edits)} files {'patched' if args.apply else 'would change'}"
          f"{', 1 file created' if creating else ''}")

    if not args.quiet_prose:
        residue = prose_residue(args.src_root)
        print(f"\nPROSE STILL NAMING A SUPERSEDED NUMBER — needs a human pass, {len(residue)} lines:")
        for line in residue:
            print(f"  {line}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
