"""Real key press/release state for the keyboard teleop, and the fallback.

WHY THIS MODULE EXISTS
----------------------
`keyboard_teleop_node` used to infer "the operator is holding W" from TERMINAL
AUTO-REPEAT: every repeat refreshed a timestamp, and a key counted as held while
that timestamp was younger than `drive_hold_sec`. That inference has two costs,
and both of them are things the operator feels:

  1. NACHLAUF / OVERSHOOT. The window cannot be shorter than the terminal's
     INITIAL repeat delay (~0.5 s on a default X11/Wayland setup), because the
     first repeat only arrives after it — a shorter window would make the
     start-off moment stutter. So `drive_hold_sec` was 0.6 s, and releasing W at
     `linear_vel_m_s` 0.5 left the robot driving for up to 0.6 s afterwards:
     up to 0.30 m of travel nobody asked for.

  2. ONE KEY AT A TIME. A terminal auto-repeats only the LAST key pressed. Hold
     W, then press A to steer: `w` stops being refreshed, and the drive dies
     after `drive_hold_sec`. Steering and driving are therefore not combinable
     in practice, however well the key-state model above them handles it.

Both costs come from the same place — auto-repeat is not key state — so both are
removed by the same change: ask the terminal for REAL key events.

THE MECHANISM: the kitty keyboard protocol (progressive enhancement, `CSI > u`),
supported by kitty, foot, ghostty, WezTerm, Alacritty and recent xterm. With
flags 1|2|8 the terminal reports EVERY key as an escape sequence carrying an
EVENT TYPE — press (1), repeat (2), release (3). Flag 8 is not optional here:
the protocol cannot report a release for a key it delivers as plain text, so
"report all keys as escape codes" is what makes releases exist at all.

Chosen over the two alternatives on this machine:
  * evdev (/dev/input/event*) gives true key state but needs membership of group
    `input` — a system change with sudo — and reads keys GLOBALLY, not just in
    the teleop terminal. It also cannot work over SSH.
  * `xset r rate` only raises the repeat rate; it does not make releases
    observable, it is X11-only (this session is Wayland), and it makes the
    robot's stopping distance depend on an operator's desktop settings.

WHAT HAPPENS ON A TERMINAL THAT DOES NOT SUPPORT IT: `KeyStateTracker` falls
back to the timestamp model — but an ADAPTIVE one. It MEASURES the terminal's
actual repeat interval per key and sets that key's hold window from the
measurement instead of from a constant sized for the worst case. At a typical
30 ms repeat the window becomes ~0.12 s rather than 0.6 s, so even the fallback
cuts the overshoot by roughly a factor of five. The conservative constant still
applies until the first repeat has been seen, which is exactly the interval the
constant was needed for.

THE DEAD-MAN CEILING IS NEVER REMOVED. Safety incident 06.07.: a latched W in a
forgotten terminal left the motors running. Release events make the dead-man
fire EARLIER, never later — `held()` requires both "no release seen" AND "an
event within the ceiling". A terminal that dies, a suspended process or a lost
SSH pipe delivers no release, and the ceiling is what still stops the robot.

Pure python: imports nothing from rclpy and nothing from the node, so the parser
and the tracker are checkable without a ROS graph or a tty
(`test/check_key_input.py`).
"""

from __future__ import annotations

import select
import sys
from typing import Dict, List, Optional, Tuple

# ── Event kinds, as the kitty protocol numbers them ─────────────────────────

PRESS = 1
REPEAT = 2
RELEASE = 3

# Progressive-enhancement flags we ask for:
#   1 = disambiguate escape codes
#   2 = report event types  (this is the one that carries press/repeat/release)
#   8 = report all keys as escape codes
# 8 is REQUIRED for 2 to be useful: a key delivered as plain text has nowhere to
# carry an event type, so without it `w` would still arrive as a bare byte and
# its release would never be reported.
_FLAGS = 1 | 2 | 8

_QUERY = "\x1b[?u"           # "do you support this?" -> replies CSI ? <flags> u
_PUSH = f"\x1b[>{_FLAGS}u"   # push our flags onto the terminal's stack
_POP = "\x1b[<u"             # pop them again on the way out

# How long to wait for the support reply. The reply is generated by the terminal
# emulator itself and comes back in well under a millisecond locally; 0.15 s is
# slack for an SSH round trip and still short enough that an unsupported
# terminal costs the operator an imperceptible pause at startup.
_QUERY_TIMEOUT_SEC = 0.15

# Unicode code points of the keys this teleop binds, for the CSI-u form.
#
# THIS TABLE MUST COVER EVERY BOUND KEY, not just the movement ones. Under
# flag 8 the terminal stops sending ANY key as plain text, so a key missing here
# is a key the operator can no longer press — the quit key and the mode keys
# included. That is why the command keys appear alongside the drive keys even
# though only the drive keys care about press/release.
_CODE_TO_KEY = {
    ord("w"): "w",
    ord("s"): "s",
    ord("a"): "a",
    ord("d"): "d",
    ord(" "): "space",
    ord("0"): "0",
    ord("9"): "9",
    ord("q"): "q",
    ord("k"): "k",
    ord("g"): "g",
    ord("p"): "p",
    ord("o"): "o",
    ord("i"): "i",
    ord("u"): "u",
    ord("l"): "l",
}

# Kitty modifier bitmask, 1-based: 1 = none, and +4 is control.
_MOD_NONE = 1
_MOD_CTRL = 5

# Functional keys keep their own final byte under this protocol; the event type
# rides in the third parameter exactly as it does for CSI-u.
_FINAL_TO_KEY = {"A": "up", "B": "down", "C": "right", "D": "left"}


# ── Sequence parsing ────────────────────────────────────────────────────────


def parse_csi(parameters: str, final: str) -> Optional[Tuple[str, int]]:
    """Decode one CSI sequence body into (key name, event kind), or None.

    `parameters` is everything between the introducer and the final byte, and
    `final` is the terminating byte. Two shapes matter:

        CSI <code> ; <mods> : <event> u     -- a text key under flag 8
        CSI 1 ; <mods> : <event> A..D       -- a cursor key

    The modifier and event fields are both optional: a terminal that only got
    flag 1 sends `CSI 119 u` with no event field at all. A MISSING EVENT FIELD
    IS REPORTED AS `PRESS`, not as unknown — under a protocol that never sends
    releases, every sequence that arrives is a key going down, and the tracker's
    fallback path handles the rest.

    Returns None for anything this teleop does not bind, including modified
    keys, so that (say) ctrl+up cannot fall through and be read as `up`.
    """

    fields = parameters.split(";") if parameters else []

    # Field 2 carries `modifiers:event`. Modifiers are 1-based (1 = none).
    # Modified keys are dropped so that ctrl+up cannot fall through as a plain
    # cursor key — with ONE exception, ctrl+C, which is a quit path and would
    # otherwise stop working the moment flag 8 takes plain bytes away.
    event = PRESS
    modifiers = _MOD_NONE
    if len(fields) >= 2:
        modifier_text, _, event_text = fields[1].partition(":")
        if modifier_text not in ("", "1"):
            try:
                modifiers = int(modifier_text)
            except ValueError:
                return None
        if event_text:
            try:
                event = int(event_text)
            except ValueError:
                return None
            if event not in (PRESS, REPEAT, RELEASE):
                return None

    if modifiers == _MOD_CTRL and final == "u" and fields:
        try:
            code = int(fields[0].partition(":")[0])
        except ValueError:
            return None
        return ("ctrl_c", event) if code == ord("c") else None
    if modifiers != _MOD_NONE:
        return None

    if final in _FINAL_TO_KEY:
        # Cursor keys. Under flag 1 the first field is the literal 1; a bare
        # `CSI A` (no parameters at all) is the pre-protocol form and is equally
        # valid, which is what keeps this parser working on both.
        if fields and fields[0] not in ("", "1"):
            return None
        return _FINAL_TO_KEY[final], event

    if final == "u":
        if not fields:
            return None
        try:
            code = int(fields[0].partition(":")[0])
        except ValueError:
            return None
        key = _CODE_TO_KEY.get(code)
        # Letters arrive as their LOWERCASE code point under this protocol
        # (shift lives in the modifier field), so no case folding is needed and
        # none is done — folding here would silently accept shifted keys that
        # the modifier check above just rejected.
        return (key, event) if key is not None else None

    return None


def read_sequence(tty_file, timeout_sec: float) -> Optional[Tuple[str, int]]:
    """Read one escape sequence, ESC already consumed. None if it is not a key.

    Deliberately tolerant of a BARE ESC — a human pressing escape produces
    nothing after it, and this must not block waiting for bytes that are never
    coming.
    """

    ready, _, _ = select.select([tty_file], [], [], timeout_sec)
    if not ready:
        return None
    introducer = tty_file.read(1).decode("utf-8", errors="ignore")
    if introducer not in ("[", "O"):
        return None

    parameters = ""
    while True:
        ready, _, _ = select.select([tty_file], [], [], timeout_sec)
        if not ready:
            return None
        byte = tty_file.read(1).decode("utf-8", errors="ignore")
        if not byte:
            return None
        # ECMA-48: 0x40..0x7E terminates a control sequence, 0x20..0x3F are
        # parameter and intermediate bytes.
        if 0x40 <= ord(byte) <= 0x7E:
            return parse_csi(parameters, byte)
        parameters += byte
        # A key sequence under this protocol is short. A runaway parameter run
        # is a corrupted stream, and continuing to accumulate it would swallow
        # every following keystroke — including the space bar.
        if len(parameters) > 16:
            return None


# ── Terminal negotiation ────────────────────────────────────────────────────


def enable_release_reporting(tty_file) -> bool:
    """Ask the terminal for press/repeat/release reporting. True if it agreed.

    MUST be called with the tty already in raw mode: the reply is an escape
    sequence, and a cooked terminal would line-buffer it and echo it to the
    operator instead of handing it over.

    A terminal that does not implement the protocol ignores the query and sends
    no reply, which is why this is a timed read rather than a blocking one.
    """

    try:
        sys.stdout.write(_QUERY)
        sys.stdout.flush()
    except (OSError, ValueError):
        return False

    ready, _, _ = select.select([tty_file], [], [], _QUERY_TIMEOUT_SEC)
    if not ready:
        return False

    # The reply is `CSI ? <flags> u`. Read it out of the stream rather than
    # leaving it to be misread as keystrokes a moment later.
    if tty_file.read(1) != b"\x1b":
        return False
    body = b""
    while len(body) < 16:
        ready, _, _ = select.select([tty_file], [], [], _QUERY_TIMEOUT_SEC)
        if not ready:
            return False
        byte = tty_file.read(1)
        if not byte:
            return False
        body += byte
        if byte == b"u":
            break
    else:
        return False

    if not body.startswith(b"[?") or not body.endswith(b"u"):
        return False

    sys.stdout.write(_PUSH)
    sys.stdout.flush()
    return True


def disable_release_reporting() -> None:
    """Pop our flags. Safe to call even if enable_release_reporting() said False.

    Popping a stack we never pushed to is a no-op in the protocol, and leaving
    the flags set would hand the operator's shell a terminal that reports every
    keystroke as an escape sequence — a broken shell, after a clean quit.
    """

    try:
        sys.stdout.write(_POP)
        sys.stdout.flush()
    except (OSError, ValueError):
        pass


# ── Key state ───────────────────────────────────────────────────────────────


class KeyStateTracker:
    """Which keys are down, from real events where they exist and timing where not.

    ONE OBJECT, TWO REGIMES, and the caller cannot tell them apart — `held()`
    answers the same question either way:

      * release_reporting=True  — a key is held from its press until its
        release, subject to the ceiling below.
      * release_reporting=False — a key is held while events keep arriving,
        with the window MEASURED from the terminal's own repeat interval
        instead of assumed.

    `ceiling_sec` is the dead-man and applies in BOTH regimes. See the module
    docstring: releases may only ever make it fire sooner.
    """

    # Multiple of the measured repeat interval that still counts as held. Two
    # would sit exactly on the next expected repeat and would drop the key on
    # any scheduling jitter; three leaves a full interval of slack and still
    # keeps the window an order of magnitude under the old constant.
    _REPEAT_SLACK = 3.0
    # Floor on the adaptive window. Below roughly this, ordinary jitter in the
    # terminal's repeat timing starts reading as a release and the drive
    # stutters — the failure the old constant was oversized to avoid.
    _MIN_WINDOW_SEC = 0.10
    # How many repeat intervals to average before trusting the measurement. One
    # sample is dominated by the initial-delay-to-first-repeat gap, which is not
    # the steady-state interval at all.
    _INTERVALS_NEEDED = 2

    def __init__(self, keys, ceiling_sec: float, release_reporting: bool) -> None:
        self.release_reporting = bool(release_reporting)
        self.ceiling_sec = float(ceiling_sec)
        self._down: Dict[str, bool] = {key: False for key in keys}
        self._last_event: Dict[str, float] = {key: 0.0 for key in keys}
        self._last_repeat: Dict[str, float] = {key: 0.0 for key in keys}
        self._intervals: Dict[str, List[float]] = {key: [] for key in keys}

    # -- ingest -----------------------------------------------------------

    def on_event(self, key: str, kind: int, now: float) -> None:
        """Record one key event. Unknown keys are ignored, not created."""

        if key not in self._down:
            return

        if kind == RELEASE:
            self._down[key] = False
            self._last_event[key] = now
            self._last_repeat[key] = 0.0
            return

        if kind == REPEAT and self._last_repeat[key] > 0.0:
            interval = now - self._last_repeat[key]
            # Guard both ends: a zero/negative interval is a duplicated event,
            # and an interval longer than the ceiling is a gap, not a repeat
            # rate — folding either into the average would corrupt the window
            # this measurement exists to set.
            if 0.0 < interval <= self.ceiling_sec:
                samples = self._intervals[key]
                samples.append(interval)
                if len(samples) > 8:
                    del samples[0]

        self._down[key] = True
        self._last_event[key] = now
        self._last_repeat[key] = now

    def press(self, key: str, now: float) -> None:
        """Convenience for callers that have no event type — treated as a press."""

        self.on_event(key, PRESS, now)

    def clear(self, key: str, now: float) -> None:
        """Force a key down-state off, as the emergency stop does.

        Kept separate from a RELEASE event on purpose: this is the code saying
        "forget this key", not the terminal saying "the operator let go".
        """

        if key not in self._down:
            return
        self._down[key] = False
        self._last_event[key] = 0.0
        self._last_repeat[key] = 0.0

    def clear_all(self, now: float) -> None:
        for key in list(self._down):
            self.clear(key, now)

    # -- query ------------------------------------------------------------

    def window(self, key: str) -> float:
        """The hold window currently in force for this key, seconds.

        With release reporting this is only the dead-man ceiling. Without it,
        it is the measured repeat interval times the slack factor, clamped into
        [_MIN_WINDOW_SEC, ceiling] — never ABOVE the ceiling, because that would
        quietly extend the dead-man past the value the operator was told about.
        """

        if self.release_reporting:
            return self.ceiling_sec
        samples = self._intervals.get(key, ())
        if len(samples) < self._INTERVALS_NEEDED:
            return self.ceiling_sec
        mean_interval = sum(samples) / len(samples)
        return max(
            self._MIN_WINDOW_SEC,
            min(self.ceiling_sec, mean_interval * self._REPEAT_SLACK),
        )

    def held(self, key: str, now: float, window_sec: Optional[float] = None) -> bool:
        """Is this key down right now?

        `window_sec` overrides the ceiling for callers that want a tighter one
        (the steering keys used a shorter window than the drive keys long before
        this module existed). It can only ever SHORTEN the answer: the measured
        window and the ceiling both still apply.
        """

        if key not in self._down:
            return False
        if not self._down[key]:
            return False

        ceiling = self.ceiling_sec if window_sec is None else min(
            self.ceiling_sec, float(window_sec)
        )
        age = now - self._last_event[key]
        if self.release_reporting:
            # The release event is the primary signal; this is the ceiling that
            # covers a terminal which died without sending one.
            return age < ceiling
        return age < min(ceiling, self.window(key))

    def any_held(self, keys, now: float) -> bool:
        return any(self.held(key, now) for key in keys)
